module.exports = {
    namespace: 'etl',
    tableName: 'Accounts_OnlyLatest',
    schema: [
        { name: 'isCodefreshAccount', type: 'BOOL' },
        { name: 'accountId', type: 'STRING' },
        { name: 'name', type: 'STRING' },
        { name: 'privateAccountOwner', type: 'STRING' },
        { name: 'runtimeEnvironment', type: 'STRING' },
        { name: 'updatedAt', type: 'TIMESTAMP' },
        { name: 'createdAt', type: 'TIMESTAMP' },
        { name: 'lastPlanUpdate', type: 'TIMESTAMP' },
        { name: 'collaboratorsLimit', type: 'NUMERIC' },
        { name: 'collaboratorsUsed', type: 'NUMERIC' },
        { name: 'dataRetention', type: 'NUMERIC' },
        { name: 'segment', type: 'STRING' },
        { name: 'pipelineConfigTemplates', type: 'BOOL' },
        { name: 'pipelineConfigClone', type: 'BOOL' },
        { name: 'pipelineConfigYamlInline', type: 'BOOL' },
        { name: 'pipelineConfigYamlGit', type: 'BOOL' },
        { name: 'pipelineConfigYamlUrl', type: 'BOOL' },
        { name: 'keepPVCsForPendingApproval', type: 'BOOL' },
        { name: 'securityInactivityThreshold', type: 'NUMERIC' },
        { name: 'isSuspended', type: 'BOOL' },
        { name: 'hasStash', type: 'BOOL' },
        { name: 'hasGithub', type: 'BOOL' },
        { name: 'hasGitlab', type: 'BOOL' },
        { name: 'hasAks', type: 'BOOL' },
        { name: 'hasGcloud', type: 'BOOL' },
        { name: 'hasDigitalOcean', type: 'BOOL' },
        { name: 'buildStrategy', type: 'STRING' },
        { name: 'buildNodes', type: 'NUMERIC' },
        { name: 'packId', type: 'STRING' },
        { name: 'packName', type: 'STRING' },
        { name: 'packDescription', type: 'STRING' },
        { name: 'concurrencyAmount', type: 'NUMERIC' },
        { name: 'concurrencyAbsorb', type: 'NUMERIC' },
        { name: 'concurrencyUnlimited', type: 'BOOL' },
        { name: 'runtimeName', type: 'STRING' },
        { name: 'runtimeOs', type: 'STRING' },
        { name: 'runtimeArchitecture', type: 'STRING' },
        { name: 'runtimeCpu', type: 'STRING' },
        { name: 'runtimeMemory', type: 'STRING' },
        { name: 'runtimeStorage', type: 'STRING' },
        { name: 'runtimeDindStorage', type: 'STRING' },
        { name: 'packDefault', type: 'STRING' },
        { name: 'isDefaultPack', type: 'BOOL' },
        { name: 'paymentPlanId', type: 'STRING' },
        { name: 'paymentPlanTrialActive', type: 'BOOL' },
        { name: 'paymentPlanTrialWillEndNotified', type: 'BOOL' },
        { name: 'paymentPlanTrialEndedNotified', type: 'BOOL' },
        { name: 'paymentPlanTrialType', type: 'STRING' },
        { name: 'paymentPlanTrialPreviousSegment', type: 'STRING' },
        { name: 'paymentPlanTrialStart', type: 'TIMESTAMP' },
        { name: 'paymentPlanTrialEnd', type: 'TIMESTAMP' },
        { name: 'paymentPlanIsWiredTransfer', type: 'BOOL' },
        { name: 'paymentPlanProvider', type: 'STRING' },
        { name: 'environments', type: 'NUMERIC' },
        { name: 'dedicatedInfrastructure', type: 'BOOL' },
        { name: 'canUsePrivateRepos', type: 'BOOL' },
        { name: 'supportPlan', type: 'STRING' },
        { name: 'increasedAttention', type: 'BOOL' },
        { name: 'localUserPasswordIDPEnabled', type: 'BOOL' },
    ]
};
